//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CatInTheApp {
	
	
	public partial class Default {
		
		protected System.Web.UI.HtmlControls.HtmlForm form1;
		
		protected System.Web.UI.WebControls.DropDownList CatBreeds;
		
		protected System.Web.UI.WebControls.Button button1;
		
		protected System.Web.UI.WebControls.Label CatName;
		
		protected System.Web.UI.WebControls.Label CatDesc;
		
		protected System.Web.UI.WebControls.Label lifeSpan;
		
		protected System.Web.UI.WebControls.Label origin;
		
		protected System.Web.UI.WebControls.Label temperament;
		
		protected System.Web.UI.WebControls.Image CatImage;
		
		protected System.Web.UI.WebControls.Literal childFriendlyControl;
		
		protected System.Web.UI.WebControls.Literal energyLevelControl;
		
		protected System.Web.UI.WebControls.Literal vocalisationControl;
		
		protected System.Web.UI.WebControls.Literal intelligenceControl;
		
		protected System.Web.UI.WebControls.HyperLink wikiLink;
	}
}
